# Generated by Django 5.0.4 on 2025-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageLookupModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_id", models.IntegerField()),
                ("slug", models.SlugField()),
                ("path", models.CharField(max_length=200)),
            ],
        ),
    ]
