# Generated by Django 5.0.4 on 2025-01-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagelookupmodel",
            old_name="path",
            new_name="template_path",
        ),
    ]
