# Generated by Django 5.0.4 on 2025-01-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_rename_path_pagelookupmodel_template_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagelookupmodel",
            name="url_base_path",
            field=models.CharField(default="/foo", max_length=200),
            preserve_default=False,
        ),
    ]
